version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install sagemaker boto3 pandas scikit-learn
  build:
    commands:
      - python iris_pipeline.py

